# Generated by Django 4.2.2 on 2023-08-20 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(default=8, upload_to='album_covers/'),
            preserve_default=False,
        ),
    ]
